//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.ServicioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.service.lkprogrammers.org/", ConfigurationName="ServicioWS.LKServicioWeb")]
    public interface LKServicioWeb {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/helloRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.helloResponse hello(WebForm.ServicioWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/helloRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/helloResponse")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.helloResponse> helloAsync(WebForm.ServicioWS.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/esTutorAsignadoRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/esTutorAsignadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.esTutorAsignadoResponse esTutorAsignado(WebForm.ServicioWS.esTutorAsignadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/esTutorAsignadoRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/esTutorAsignadoResponse")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.esTutorAsignadoResponse> esTutorAsignadoAsync(WebForm.ServicioWS.esTutorAsignadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/listarProfesoresRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/listarProfesoresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.listarProfesoresResponse listarProfesores(WebForm.ServicioWS.listarProfesoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/listarProfesoresRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/listarProfesoresResponse")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.listarProfesoresResponse> listarProfesoresAsync(WebForm.ServicioWS.listarProfesoresRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/listarAlumnosRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/listarAlumnosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.listarAlumnosResponse listarAlumnos(WebForm.ServicioWS.listarAlumnosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/listarAlumnosRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/listarAlumnosResponse")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.listarAlumnosResponse> listarAlumnosAsync(WebForm.ServicioWS.listarAlumnosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/listarUsuariosRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/listarUsuariosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.listarUsuariosResponse listarUsuarios(WebForm.ServicioWS.listarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/listarUsuariosRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/listarUsuariosResponse")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.listarUsuariosResponse> listarUsuariosAsync(WebForm.ServicioWS.listarUsuariosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/insertarAsistenciaRequest" +
            "", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/insertarAsistenciaRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.insertarAsistenciaResponse insertarAsistencia(WebForm.ServicioWS.insertarAsistenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/insertarAsistenciaRequest" +
            "", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/insertarAsistenciaRespons" +
            "e")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.insertarAsistenciaResponse> insertarAsistenciaAsync(WebForm.ServicioWS.insertarAsistenciaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/listarAdministradoresRequ" +
            "est", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/listarAdministradoresResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.listarAdministradoresResponse listarAdministradores(WebForm.ServicioWS.listarAdministradoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/listarAdministradoresRequ" +
            "est", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/listarAdministradoresResp" +
            "onse")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.listarAdministradoresResponse> listarAdministradoresAsync(WebForm.ServicioWS.listarAdministradoresRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/listarAlumnosxsalonReques" +
            "t", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/listarAlumnosxsalonRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.listarAlumnosxsalonResponse listarAlumnosxsalon(WebForm.ServicioWS.listarAlumnosxsalonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/listarAlumnosxsalonReques" +
            "t", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/listarAlumnosxsalonRespon" +
            "se")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.listarAlumnosxsalonResponse> listarAlumnosxsalonAsync(WebForm.ServicioWS.listarAlumnosxsalonRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/insertaTodasAsistenciasRe" +
            "quest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/insertaTodasAsistenciasRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.insertaTodasAsistenciasResponse insertaTodasAsistencias(WebForm.ServicioWS.insertaTodasAsistenciasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/insertaTodasAsistenciasRe" +
            "quest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/insertaTodasAsistenciasRe" +
            "sponse")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.insertaTodasAsistenciasResponse> insertaTodasAsistenciasAsync(WebForm.ServicioWS.insertaTodasAsistenciasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/eliminarAlumnoRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/eliminarAlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.eliminarAlumnoResponse eliminarAlumno(WebForm.ServicioWS.eliminarAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/eliminarAlumnoRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/eliminarAlumnoResponse")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.eliminarAlumnoResponse> eliminarAlumnoAsync(WebForm.ServicioWS.eliminarAlumnoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/eliminarProfesorRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/eliminarProfesorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.eliminarProfesorResponse eliminarProfesor(WebForm.ServicioWS.eliminarProfesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/eliminarProfesorRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/eliminarProfesorResponse")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.eliminarProfesorResponse> eliminarProfesorAsync(WebForm.ServicioWS.eliminarProfesorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/reporteGeneralNotasAlumno" +
            "Request", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/reporteGeneralNotasAlumno" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.reporteGeneralNotasAlumnoResponse reporteGeneralNotasAlumno(WebForm.ServicioWS.reporteGeneralNotasAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/reporteGeneralNotasAlumno" +
            "Request", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/reporteGeneralNotasAlumno" +
            "Response")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.reporteGeneralNotasAlumnoResponse> reporteGeneralNotasAlumnoAsync(WebForm.ServicioWS.reporteGeneralNotasAlumnoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/insertarprofesorRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/insertarprofesorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.insertarprofesorResponse insertarprofesor(WebForm.ServicioWS.insertarprofesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/insertarprofesorRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/insertarprofesorResponse")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.insertarprofesorResponse> insertarprofesorAsync(WebForm.ServicioWS.insertarprofesorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/editarAlumnoRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/editarAlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.editarAlumnoResponse editarAlumno(WebForm.ServicioWS.editarAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/editarAlumnoRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/editarAlumnoResponse")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.editarAlumnoResponse> editarAlumnoAsync(WebForm.ServicioWS.editarAlumnoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/editarProfesorRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/editarProfesorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.editarProfesorResponse editarProfesor(WebForm.ServicioWS.editarProfesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/editarProfesorRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/editarProfesorResponse")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.editarProfesorResponse> editarProfesorAsync(WebForm.ServicioWS.editarProfesorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/insertarAlumnoRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/insertarAlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.insertarAlumnoResponse insertarAlumno(WebForm.ServicioWS.insertarAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/insertarAlumnoRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/insertarAlumnoResponse")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.insertarAlumnoResponse> insertarAlumnoAsync(WebForm.ServicioWS.insertarAlumnoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/verificarUsuarioRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/verificarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebForm.ServicioWS.verificarUsuarioResponse verificarUsuario(WebForm.ServicioWS.verificarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.service.lkprogrammers.org/LKServicioWeb/verificarUsuarioRequest", ReplyAction="http://services.service.lkprogrammers.org/LKServicioWeb/verificarUsuarioResponse")]
        System.Threading.Tasks.Task<WebForm.ServicioWS.verificarUsuarioResponse> verificarUsuarioAsync(WebForm.ServicioWS.verificarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="esTutorAsignado", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class esTutorAsignadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dniProfesor;
        
        public esTutorAsignadoRequest() {
        }
        
        public esTutorAsignadoRequest(string dniProfesor) {
            this.dniProfesor = dniProfesor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="esTutorAsignadoResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class esTutorAsignadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public esTutorAsignadoResponse() {
        }
        
        public esTutorAsignadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.service.lkprogrammers.org/")]
    public partial class alumno : usuario {
        
        private int codigoAlumnoField;
        
        private grado gradoField;
        
        private bool gradoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAlumno {
            get {
                return this.codigoAlumnoField;
            }
            set {
                this.codigoAlumnoField = value;
                this.RaisePropertyChanged("codigoAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public grado grado {
            get {
                return this.gradoField;
            }
            set {
                this.gradoField = value;
                this.RaisePropertyChanged("grado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gradoSpecified {
            get {
                return this.gradoFieldSpecified;
            }
            set {
                this.gradoFieldSpecified = value;
                this.RaisePropertyChanged("gradoSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.service.lkprogrammers.org/")]
    public enum grado {
        
        /// <remarks/>
        NN,
        
        /// <remarks/>
        INI2,
        
        /// <remarks/>
        INI3,
        
        /// <remarks/>
        INI4,
        
        /// <remarks/>
        INI5,
        
        /// <remarks/>
        PRIM1,
        
        /// <remarks/>
        PRIM2,
        
        /// <remarks/>
        PRIM3,
        
        /// <remarks/>
        PRIM4,
        
        /// <remarks/>
        PRIM5,
        
        /// <remarks/>
        PRIM6,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(alumno))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personalAdministrativo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(profesor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.service.lkprogrammers.org/")]
    public abstract partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string contraseniaField;
        
        private string correoElectronicoField;
        
        private string direccionField;
        
        private string dniField;
        
        private System.DateTime fechaNacField;
        
        private bool fechaNacFieldSpecified;
        
        private ushort generoField;
        
        private string nombresField;
        
        private string telefonoField;
        
        private string usuario1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                this.contraseniaField = value;
                this.RaisePropertyChanged("contrasenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
                this.RaisePropertyChanged("correoElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaNac {
            get {
                return this.fechaNacField;
            }
            set {
                this.fechaNacField = value;
                this.RaisePropertyChanged("fechaNac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacSpecified {
            get {
                return this.fechaNacFieldSpecified;
            }
            set {
                this.fechaNacFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public ushort genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("usuario", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string usuario1 {
            get {
                return this.usuario1Field;
            }
            set {
                this.usuario1Field = value;
                this.RaisePropertyChanged("usuario1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.service.lkprogrammers.org/")]
    public partial class asistencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dniAlumnoField;
        
        private estadoAsistencia estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaHoraField;
        
        private bool fechaHoraFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dniAlumno {
            get {
                return this.dniAlumnoField;
            }
            set {
                this.dniAlumnoField = value;
                this.RaisePropertyChanged("dniAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoAsistencia estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaHoraSpecified {
            get {
                return this.fechaHoraFieldSpecified;
            }
            set {
                this.fechaHoraFieldSpecified = value;
                this.RaisePropertyChanged("fechaHoraSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.service.lkprogrammers.org/")]
    public enum estadoAsistencia {
        
        /// <remarks/>
        Presente,
        
        /// <remarks/>
        Tardanza,
        
        /// <remarks/>
        Ausente,
        
        /// <remarks/>
        Justificada,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.service.lkprogrammers.org/")]
    public partial class alumno : usuario {
        
        private int codigoProfesorField;
        
        private string especialidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoProfesor {
            get {
                return this.codigoProfesorField;
            }
            set {
                this.codigoProfesorField = value;
                this.RaisePropertyChanged("codigoProfesor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gradoSpecified {
            get {
                return this.gradoFieldSpecified;
            }
            set {
                this.gradoFieldSpecified = value;
                this.RaisePropertyChanged("gradoSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.service.lkprogrammers.org/")]
    public enum grado {
        
        /// <remarks/>
        NN,
        
        /// <remarks/>
        INI2,
        
        /// <remarks/>
        INI3,
        
        /// <remarks/>
        INI4,
        
        /// <remarks/>
        INI5,
        
        /// <remarks/>
        PRIM1,
        
        /// <remarks/>
        PRIM2,
        
        /// <remarks/>
        PRIM3,
        
        /// <remarks/>
        PRIM4,
        
        /// <remarks/>
        PRIM5,
        
        /// <remarks/>
        PRIM6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.service.lkprogrammers.org/")]
    public partial class personalAdministrativo : usuario {
        
        private int codigoPersonalField;
        
        private string puestoEjecutivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoPersonal {
            get {
                return this.codigoPersonalField;
            }
            set {
                this.codigoPersonalField = value;
                this.RaisePropertyChanged("codigoPersonal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string puestoEjecutivo {
            get {
                return this.puestoEjecutivoField;
            }
            set {
                this.puestoEjecutivoField = value;
                this.RaisePropertyChanged("puestoEjecutivo");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProfesores", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class listarProfesoresRequest {
        
        public listarProfesoresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProfesoresResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class listarProfesoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebForm.ServicioWS.profesor[] @return;
        
        public listarProfesoresResponse() {
        }
        
        public listarProfesoresResponse(WebForm.ServicioWS.profesor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlumnos", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class listarAlumnosRequest {
        
        public listarAlumnosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlumnosResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class listarAlumnosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebForm.ServicioWS.alumno[] @return;
        
        public listarAlumnosResponse() {
        }
        
        public listarAlumnosResponse(WebForm.ServicioWS.alumno[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuarios", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class listarUsuariosRequest {
        
        public listarUsuariosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuariosResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class listarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebForm.ServicioWS.usuario[] @return;
        
        public listarUsuariosResponse() {
        }
        
        public listarUsuariosResponse(WebForm.ServicioWS.usuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAsistencia", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class insertarAsistenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebForm.ServicioWS.asistencia asistencia;
        
        public insertarAsistenciaRequest() {
        }
        
        public insertarAsistenciaRequest(WebForm.ServicioWS.asistencia asistencia) {
            this.asistencia = asistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAsistenciaResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class insertarAsistenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarAsistenciaResponse() {
        }
        
        public insertarAsistenciaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAdministradores", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class listarAdministradoresRequest {
        
        public listarAdministradoresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAdministradoresResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class listarAdministradoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebForm.ServicioWS.personalAdministrativo[] @return;
        
        public listarAdministradoresResponse() {
        }
        
        public listarAdministradoresResponse(WebForm.ServicioWS.personalAdministrativo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlumnosxsalon", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class listarAlumnosxsalonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSalon;
        
        public listarAlumnosxsalonRequest() {
        }
        
        public listarAlumnosxsalonRequest(int idSalon) {
            this.idSalon = idSalon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlumnosxsalonResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class listarAlumnosxsalonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebForm.ServicioWS.alumno[] @return;
        
        public listarAlumnosxsalonResponse() {
        }
        
        public listarAlumnosxsalonResponse(WebForm.ServicioWS.alumno[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertaTodasAsistencias", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class insertaTodasAsistenciasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebForm.ServicioWS.asistencia[] arg0;
        
        public insertaTodasAsistenciasRequest() {
        }
        
        public insertaTodasAsistenciasRequest(WebForm.ServicioWS.asistencia[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertaTodasAsistenciasResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class insertaTodasAsistenciasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertaTodasAsistenciasResponse() {
        }
        
        public insertaTodasAsistenciasResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAlumno", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class eliminarAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarAlumnoRequest() {
        }
        
        public eliminarAlumnoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAlumnoResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class eliminarAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarAlumnoResponse() {
        }
        
        public eliminarAlumnoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProfesor", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class eliminarProfesorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarProfesorRequest() {
        }
        
        public eliminarProfesorRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProfesorResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class eliminarProfesorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarProfesorResponse() {
        }
        
        public eliminarProfesorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteGeneralNotasAlumno", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class reporteGeneralNotasAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoAlumno;
        
        public reporteGeneralNotasAlumnoRequest() {
        }
        
        public reporteGeneralNotasAlumnoRequest(int codigoAlumno) {
            this.codigoAlumno = codigoAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteGeneralNotasAlumnoResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class reporteGeneralNotasAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebForm.ServicioWS.alumno @return;
        
        public reporteGeneralNotasAlumnoResponse() {
        }
        
        public reporteGeneralNotasAlumnoResponse(WebForm.ServicioWS.alumno @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarprofesor", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class insertarprofesorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebForm.ServicioWS.profesor arg0;
        
        public insertarprofesorRequest() {
        }
        
        public insertarprofesorRequest(WebForm.ServicioWS.profesor arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarprofesorResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class insertarprofesorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarprofesorResponse() {
        }
        
        public insertarprofesorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editarAlumno", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class editarAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebForm.ServicioWS.alumno arg0;
        
        public editarAlumnoRequest() {
        }
        
        public editarAlumnoRequest(WebForm.ServicioWS.alumno arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editarAlumnoResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class editarAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public editarAlumnoResponse() {
        }
        
        public editarAlumnoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editarProfesor", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class editarProfesorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebForm.ServicioWS.profesor arg0;
        
        public editarProfesorRequest() {
        }
        
        public editarProfesorRequest(WebForm.ServicioWS.profesor arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editarProfesorResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class editarProfesorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public editarProfesorResponse() {
        }
        
        public editarProfesorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAlumno", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class insertarAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebForm.ServicioWS.alumno arg0;
        
        public insertarAlumnoRequest() {
        }
        
        public insertarAlumnoRequest(WebForm.ServicioWS.alumno arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAlumnoResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class insertarAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarAlumnoResponse() {
        }
        
        public insertarAlumnoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarUsuario", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class verificarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenia;
        
        public verificarUsuarioRequest() {
        }
        
        public verificarUsuarioRequest(string usuario, string contrasenia) {
            this.usuario = usuario;
            this.contrasenia = contrasenia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarUsuarioResponse", WrapperNamespace="http://services.service.lkprogrammers.org/", IsWrapped=true)]
    public partial class verificarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.service.lkprogrammers.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebForm.ServicioWS.usuario @return;
        
        public verificarUsuarioResponse() {
        }
        
        public verificarUsuarioResponse(WebForm.ServicioWS.usuario @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LKServicioWebChannel : WebForm.ServicioWS.LKServicioWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LKServicioWebClient : System.ServiceModel.ClientBase<WebForm.ServicioWS.LKServicioWeb>, WebForm.ServicioWS.LKServicioWeb {
        
        public LKServicioWebClient() {
        }
        
        public LKServicioWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LKServicioWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LKServicioWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LKServicioWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.helloResponse WebForm.ServicioWS.LKServicioWeb.hello(WebForm.ServicioWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WebForm.ServicioWS.helloRequest inValue = new WebForm.ServicioWS.helloRequest();
            inValue.name = name;
            WebForm.ServicioWS.helloResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.helloResponse> WebForm.ServicioWS.LKServicioWeb.helloAsync(WebForm.ServicioWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.helloResponse> helloAsync(string name) {
            WebForm.ServicioWS.helloRequest inValue = new WebForm.ServicioWS.helloRequest();
            inValue.name = name;
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.esTutorAsignadoResponse WebForm.ServicioWS.LKServicioWeb.esTutorAsignado(WebForm.ServicioWS.esTutorAsignadoRequest request) {
            return base.Channel.esTutorAsignado(request);
        }
        
        public int esTutorAsignado(string dniProfesor) {
            WebForm.ServicioWS.esTutorAsignadoRequest inValue = new WebForm.ServicioWS.esTutorAsignadoRequest();
            inValue.dniProfesor = dniProfesor;
            WebForm.ServicioWS.esTutorAsignadoResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).esTutorAsignado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.esTutorAsignadoResponse> WebForm.ServicioWS.LKServicioWeb.esTutorAsignadoAsync(WebForm.ServicioWS.esTutorAsignadoRequest request) {
            return base.Channel.esTutorAsignadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.esTutorAsignadoResponse> esTutorAsignadoAsync(string dniProfesor) {
            WebForm.ServicioWS.esTutorAsignadoRequest inValue = new WebForm.ServicioWS.esTutorAsignadoRequest();
            inValue.dniProfesor = dniProfesor;
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).esTutorAsignadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.listarProfesoresResponse WebForm.ServicioWS.LKServicioWeb.listarProfesores(WebForm.ServicioWS.listarProfesoresRequest request) {
            return base.Channel.listarProfesores(request);
        }
        
        public WebForm.ServicioWS.profesor[] listarProfesores() {
            WebForm.ServicioWS.listarProfesoresRequest inValue = new WebForm.ServicioWS.listarProfesoresRequest();
            WebForm.ServicioWS.listarProfesoresResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).listarProfesores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.listarProfesoresResponse> WebForm.ServicioWS.LKServicioWeb.listarProfesoresAsync(WebForm.ServicioWS.listarProfesoresRequest request) {
            return base.Channel.listarProfesoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.listarProfesoresResponse> listarProfesoresAsync() {
            WebForm.ServicioWS.listarProfesoresRequest inValue = new WebForm.ServicioWS.listarProfesoresRequest();
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).listarProfesoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.listarAlumnosResponse WebForm.ServicioWS.LKServicioWeb.listarAlumnos(WebForm.ServicioWS.listarAlumnosRequest request) {
            return base.Channel.listarAlumnos(request);
        }
        
        public WebForm.ServicioWS.alumno[] listarAlumnos() {
            WebForm.ServicioWS.listarAlumnosRequest inValue = new WebForm.ServicioWS.listarAlumnosRequest();
            WebForm.ServicioWS.listarAlumnosResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).listarAlumnos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.listarAlumnosResponse> WebForm.ServicioWS.LKServicioWeb.listarAlumnosAsync(WebForm.ServicioWS.listarAlumnosRequest request) {
            return base.Channel.listarAlumnosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.listarAlumnosResponse> listarAlumnosAsync() {
            WebForm.ServicioWS.listarAlumnosRequest inValue = new WebForm.ServicioWS.listarAlumnosRequest();
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).listarAlumnosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.listarUsuariosResponse WebForm.ServicioWS.LKServicioWeb.listarUsuarios(WebForm.ServicioWS.listarUsuariosRequest request) {
            return base.Channel.listarUsuarios(request);
        }
        
        public WebForm.ServicioWS.usuario[] listarUsuarios() {
            WebForm.ServicioWS.listarUsuariosRequest inValue = new WebForm.ServicioWS.listarUsuariosRequest();
            WebForm.ServicioWS.listarUsuariosResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).listarUsuarios(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.listarUsuariosResponse> WebForm.ServicioWS.LKServicioWeb.listarUsuariosAsync(WebForm.ServicioWS.listarUsuariosRequest request) {
            return base.Channel.listarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.listarUsuariosResponse> listarUsuariosAsync() {
            WebForm.ServicioWS.listarUsuariosRequest inValue = new WebForm.ServicioWS.listarUsuariosRequest();
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).listarUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.insertarAsistenciaResponse WebForm.ServicioWS.LKServicioWeb.insertarAsistencia(WebForm.ServicioWS.insertarAsistenciaRequest request) {
            return base.Channel.insertarAsistencia(request);
        }
        
        public int insertarAsistencia(WebForm.ServicioWS.asistencia asistencia) {
            WebForm.ServicioWS.insertarAsistenciaRequest inValue = new WebForm.ServicioWS.insertarAsistenciaRequest();
            inValue.asistencia = asistencia;
            WebForm.ServicioWS.insertarAsistenciaResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).insertarAsistencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.insertarAsistenciaResponse> WebForm.ServicioWS.LKServicioWeb.insertarAsistenciaAsync(WebForm.ServicioWS.insertarAsistenciaRequest request) {
            return base.Channel.insertarAsistenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.insertarAsistenciaResponse> insertarAsistenciaAsync(WebForm.ServicioWS.asistencia asistencia) {
            WebForm.ServicioWS.insertarAsistenciaRequest inValue = new WebForm.ServicioWS.insertarAsistenciaRequest();
            inValue.asistencia = asistencia;
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).insertarAsistenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.listarAdministradoresResponse WebForm.ServicioWS.LKServicioWeb.listarAdministradores(WebForm.ServicioWS.listarAdministradoresRequest request) {
            return base.Channel.listarAdministradores(request);
        }
        
        public WebForm.ServicioWS.personalAdministrativo[] listarAdministradores() {
            WebForm.ServicioWS.listarAdministradoresRequest inValue = new WebForm.ServicioWS.listarAdministradoresRequest();
            WebForm.ServicioWS.listarAdministradoresResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).listarAdministradores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.listarAdministradoresResponse> WebForm.ServicioWS.LKServicioWeb.listarAdministradoresAsync(WebForm.ServicioWS.listarAdministradoresRequest request) {
            return base.Channel.listarAdministradoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.listarAdministradoresResponse> listarAdministradoresAsync() {
            WebForm.ServicioWS.listarAdministradoresRequest inValue = new WebForm.ServicioWS.listarAdministradoresRequest();
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).listarAdministradoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.listarAlumnosxsalonResponse WebForm.ServicioWS.LKServicioWeb.listarAlumnosxsalon(WebForm.ServicioWS.listarAlumnosxsalonRequest request) {
            return base.Channel.listarAlumnosxsalon(request);
        }
        
        public WebForm.ServicioWS.alumno[] listarAlumnosxsalon(int idSalon) {
            WebForm.ServicioWS.listarAlumnosxsalonRequest inValue = new WebForm.ServicioWS.listarAlumnosxsalonRequest();
            inValue.idSalon = idSalon;
            WebForm.ServicioWS.listarAlumnosxsalonResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).listarAlumnosxsalon(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.listarAlumnosxsalonResponse> WebForm.ServicioWS.LKServicioWeb.listarAlumnosxsalonAsync(WebForm.ServicioWS.listarAlumnosxsalonRequest request) {
            return base.Channel.listarAlumnosxsalonAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.listarAlumnosxsalonResponse> listarAlumnosxsalonAsync(int idSalon) {
            WebForm.ServicioWS.listarAlumnosxsalonRequest inValue = new WebForm.ServicioWS.listarAlumnosxsalonRequest();
            inValue.idSalon = idSalon;
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).listarAlumnosxsalonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.insertaTodasAsistenciasResponse WebForm.ServicioWS.LKServicioWeb.insertaTodasAsistencias(WebForm.ServicioWS.insertaTodasAsistenciasRequest request) {
            return base.Channel.insertaTodasAsistencias(request);
        }
        
        public int insertaTodasAsistencias(WebForm.ServicioWS.asistencia[] arg0) {
            WebForm.ServicioWS.insertaTodasAsistenciasRequest inValue = new WebForm.ServicioWS.insertaTodasAsistenciasRequest();
            inValue.arg0 = arg0;
            WebForm.ServicioWS.insertaTodasAsistenciasResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).insertaTodasAsistencias(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.insertaTodasAsistenciasResponse> WebForm.ServicioWS.LKServicioWeb.insertaTodasAsistenciasAsync(WebForm.ServicioWS.insertaTodasAsistenciasRequest request) {
            return base.Channel.insertaTodasAsistenciasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.insertaTodasAsistenciasResponse> insertaTodasAsistenciasAsync(WebForm.ServicioWS.asistencia[] arg0) {
            WebForm.ServicioWS.insertaTodasAsistenciasRequest inValue = new WebForm.ServicioWS.insertaTodasAsistenciasRequest();
            inValue.arg0 = arg0;
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).insertaTodasAsistenciasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.eliminarAlumnoResponse WebForm.ServicioWS.LKServicioWeb.eliminarAlumno(WebForm.ServicioWS.eliminarAlumnoRequest request) {
            return base.Channel.eliminarAlumno(request);
        }
        
        public int eliminarAlumno(int arg0) {
            WebForm.ServicioWS.eliminarAlumnoRequest inValue = new WebForm.ServicioWS.eliminarAlumnoRequest();
            inValue.arg0 = arg0;
            WebForm.ServicioWS.eliminarAlumnoResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).eliminarAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.eliminarAlumnoResponse> WebForm.ServicioWS.LKServicioWeb.eliminarAlumnoAsync(WebForm.ServicioWS.eliminarAlumnoRequest request) {
            return base.Channel.eliminarAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.eliminarAlumnoResponse> eliminarAlumnoAsync(int arg0) {
            WebForm.ServicioWS.eliminarAlumnoRequest inValue = new WebForm.ServicioWS.eliminarAlumnoRequest();
            inValue.arg0 = arg0;
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).eliminarAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.eliminarProfesorResponse WebForm.ServicioWS.LKServicioWeb.eliminarProfesor(WebForm.ServicioWS.eliminarProfesorRequest request) {
            return base.Channel.eliminarProfesor(request);
        }
        
        public int eliminarProfesor(int arg0) {
            WebForm.ServicioWS.eliminarProfesorRequest inValue = new WebForm.ServicioWS.eliminarProfesorRequest();
            inValue.arg0 = arg0;
            WebForm.ServicioWS.eliminarProfesorResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).eliminarProfesor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.eliminarProfesorResponse> WebForm.ServicioWS.LKServicioWeb.eliminarProfesorAsync(WebForm.ServicioWS.eliminarProfesorRequest request) {
            return base.Channel.eliminarProfesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.eliminarProfesorResponse> eliminarProfesorAsync(int arg0) {
            WebForm.ServicioWS.eliminarProfesorRequest inValue = new WebForm.ServicioWS.eliminarProfesorRequest();
            inValue.arg0 = arg0;
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).eliminarProfesorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.reporteGeneralNotasAlumnoResponse WebForm.ServicioWS.LKServicioWeb.reporteGeneralNotasAlumno(WebForm.ServicioWS.reporteGeneralNotasAlumnoRequest request) {
            return base.Channel.reporteGeneralNotasAlumno(request);
        }
        
        public WebForm.ServicioWS.alumno reporteGeneralNotasAlumno(int codigoAlumno) {
            WebForm.ServicioWS.reporteGeneralNotasAlumnoRequest inValue = new WebForm.ServicioWS.reporteGeneralNotasAlumnoRequest();
            inValue.codigoAlumno = codigoAlumno;
            WebForm.ServicioWS.reporteGeneralNotasAlumnoResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).reporteGeneralNotasAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.reporteGeneralNotasAlumnoResponse> WebForm.ServicioWS.LKServicioWeb.reporteGeneralNotasAlumnoAsync(WebForm.ServicioWS.reporteGeneralNotasAlumnoRequest request) {
            return base.Channel.reporteGeneralNotasAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.reporteGeneralNotasAlumnoResponse> reporteGeneralNotasAlumnoAsync(int codigoAlumno) {
            WebForm.ServicioWS.reporteGeneralNotasAlumnoRequest inValue = new WebForm.ServicioWS.reporteGeneralNotasAlumnoRequest();
            inValue.codigoAlumno = codigoAlumno;
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).reporteGeneralNotasAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.insertarprofesorResponse WebForm.ServicioWS.LKServicioWeb.insertarprofesor(WebForm.ServicioWS.insertarprofesorRequest request) {
            return base.Channel.insertarprofesor(request);
        }
        
        public int insertarprofesor(WebForm.ServicioWS.profesor arg0) {
            WebForm.ServicioWS.insertarprofesorRequest inValue = new WebForm.ServicioWS.insertarprofesorRequest();
            inValue.arg0 = arg0;
            WebForm.ServicioWS.insertarprofesorResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).insertarprofesor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.insertarprofesorResponse> WebForm.ServicioWS.LKServicioWeb.insertarprofesorAsync(WebForm.ServicioWS.insertarprofesorRequest request) {
            return base.Channel.insertarprofesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.insertarprofesorResponse> insertarprofesorAsync(WebForm.ServicioWS.profesor arg0) {
            WebForm.ServicioWS.insertarprofesorRequest inValue = new WebForm.ServicioWS.insertarprofesorRequest();
            inValue.arg0 = arg0;
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).insertarprofesorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.editarAlumnoResponse WebForm.ServicioWS.LKServicioWeb.editarAlumno(WebForm.ServicioWS.editarAlumnoRequest request) {
            return base.Channel.editarAlumno(request);
        }
        
        public int editarAlumno(WebForm.ServicioWS.alumno arg0) {
            WebForm.ServicioWS.editarAlumnoRequest inValue = new WebForm.ServicioWS.editarAlumnoRequest();
            inValue.arg0 = arg0;
            WebForm.ServicioWS.editarAlumnoResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).editarAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.editarAlumnoResponse> WebForm.ServicioWS.LKServicioWeb.editarAlumnoAsync(WebForm.ServicioWS.editarAlumnoRequest request) {
            return base.Channel.editarAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.editarAlumnoResponse> editarAlumnoAsync(WebForm.ServicioWS.alumno arg0) {
            WebForm.ServicioWS.editarAlumnoRequest inValue = new WebForm.ServicioWS.editarAlumnoRequest();
            inValue.arg0 = arg0;
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).editarAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.editarProfesorResponse WebForm.ServicioWS.LKServicioWeb.editarProfesor(WebForm.ServicioWS.editarProfesorRequest request) {
            return base.Channel.editarProfesor(request);
        }
        
        public int editarProfesor(WebForm.ServicioWS.profesor arg0) {
            WebForm.ServicioWS.editarProfesorRequest inValue = new WebForm.ServicioWS.editarProfesorRequest();
            inValue.arg0 = arg0;
            WebForm.ServicioWS.editarProfesorResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).editarProfesor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.editarProfesorResponse> WebForm.ServicioWS.LKServicioWeb.editarProfesorAsync(WebForm.ServicioWS.editarProfesorRequest request) {
            return base.Channel.editarProfesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.editarProfesorResponse> editarProfesorAsync(WebForm.ServicioWS.profesor arg0) {
            WebForm.ServicioWS.editarProfesorRequest inValue = new WebForm.ServicioWS.editarProfesorRequest();
            inValue.arg0 = arg0;
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).editarProfesorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.insertarAlumnoResponse WebForm.ServicioWS.LKServicioWeb.insertarAlumno(WebForm.ServicioWS.insertarAlumnoRequest request) {
            return base.Channel.insertarAlumno(request);
        }
        
        public int insertarAlumno(WebForm.ServicioWS.alumno arg0) {
            WebForm.ServicioWS.insertarAlumnoRequest inValue = new WebForm.ServicioWS.insertarAlumnoRequest();
            inValue.arg0 = arg0;
            WebForm.ServicioWS.insertarAlumnoResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).insertarAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.insertarAlumnoResponse> WebForm.ServicioWS.LKServicioWeb.insertarAlumnoAsync(WebForm.ServicioWS.insertarAlumnoRequest request) {
            return base.Channel.insertarAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.insertarAlumnoResponse> insertarAlumnoAsync(WebForm.ServicioWS.alumno arg0) {
            WebForm.ServicioWS.insertarAlumnoRequest inValue = new WebForm.ServicioWS.insertarAlumnoRequest();
            inValue.arg0 = arg0;
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).insertarAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.ServicioWS.verificarUsuarioResponse WebForm.ServicioWS.LKServicioWeb.verificarUsuario(WebForm.ServicioWS.verificarUsuarioRequest request) {
            return base.Channel.verificarUsuario(request);
        }
        
        public WebForm.ServicioWS.usuario verificarUsuario(string usuario, string contrasenia) {
            WebForm.ServicioWS.verificarUsuarioRequest inValue = new WebForm.ServicioWS.verificarUsuarioRequest();
            inValue.usuario = usuario;
            inValue.contrasenia = contrasenia;
            WebForm.ServicioWS.verificarUsuarioResponse retVal = ((WebForm.ServicioWS.LKServicioWeb)(this)).verificarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.ServicioWS.verificarUsuarioResponse> WebForm.ServicioWS.LKServicioWeb.verificarUsuarioAsync(WebForm.ServicioWS.verificarUsuarioRequest request) {
            return base.Channel.verificarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.ServicioWS.verificarUsuarioResponse> verificarUsuarioAsync(string usuario, string contrasenia) {
            WebForm.ServicioWS.verificarUsuarioRequest inValue = new WebForm.ServicioWS.verificarUsuarioRequest();
            inValue.usuario = usuario;
            inValue.contrasenia = contrasenia;
            return ((WebForm.ServicioWS.LKServicioWeb)(this)).verificarUsuarioAsync(inValue);
        }
    }
}
